### ISSUE TITLE
Set up logging for the k8s pods.

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/ml-deployment-k8s-fastapi#24]

**Comment by deep-diver** [comment]
Sounds like setting up Grafana?

**Comment by deep-diver** [comment]
Sounds good! It looks like the log for pods are automatically available (not sure tho)

**Comment by sayakpaul** [comment]
That is what I assume too. In thay case, I think it'd make sense for us to show the users which places to look for to get the pod logs.
