### ISSUE TITLE
Perform load testing with Locust

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/ml-deployment-k8s-fastapi#26]
Resources:

* https://towardsdatascience.com/performance-testing-an-ml-serving-api-with-locust-ecd98ab9b7f7
* https://microsoft.github.io/PartsUnlimitedMRP/pandp/200.1x-PandP-LocustTest.html
* https://github.com/https-deeplearning-ai/machine-learning-engineering-for-production-public/tree/main/course4/week2-ungraded-labs/C4_W2_Lab_3_Latency_Test_Compose

**Comment by deep-diver** [comment]
Need to calculate some metrics like QPI(Queries Per Inference)

**Comment by sayakpaul** [comment]
Here's another wonderful resource: https://cloud.google.com/architecture/load-testing-and-monitoring-aiplatform-models.

**Comment by deep-diver** [comment]
Experiment #1 setup (TBD, WIP)

- VM (Custom Spec) for GKE nodes: 2vCPU, 4GB RAM, 100GB Storage
  - the ONNX model size is 100MB
- # of Workers: 1 (using uvicorn)
- # of Replicas: 8
- # of Users: 100
- Hatch Rate: 5

vs

- VM (Custom Spec) for GKE nodes: 8vCPU, 16GB RAM, 100GB Storage
- # of Workers: 4 (using guicorn)
- # of Replicas: 2
- # of Users: 100
- Hatch Rate: 5

vs

- VM (Custom Spec) for GKE nodes: 16vCPU, 32GB RAM, 100GB Storage
- # of Workers: 8 (using guicorn)
- # of Replicas: 1
- # of Users: 100
- Hatch Rate: 5

**Comment by sayakpaul** [comment]
@deep-diver to specify the number of workers for uvicorn and gunicorn separately I guess that change needs to happen at Dockerfile level?

Also, it would be great to know the Locust setup you are following so that I can also take part. 

Once the GKE clusters are created for each of the setup you mentioned we can distribute the workload. WDYT?

**Comment by deep-diver** [comment]
@sayakpaul 

sure thing! I will create a PR for the Locust stuff (it has just few lines of code). Also, you are right. The change needs to happen at Dockerfile level for gunicorn setup.

**Comment by sayakpaul** [comment]
Cool. For making sure we are following the setup for running the load-tests, I think this is going to be immensely helpful.

**Comment by sayakpaul** [comment]
Cool. Maybe add a note on how to interpret them?

**Comment by sayakpaul** [comment]
Or we could host the report as a GitHub Release artifact to have the repo structure clean and precise. WDYT?

**Comment by sayakpaul** [comment]
We have performed extensive load-testing. See `locust` directory.
