### ISSUE TITLE
Provision namespacing in the k8s deployment

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/ml-deployment-k8s-fastapi#27]

**Comment by deep-diver** [comment]
What is this for? Like isolation? If so can you add some more comments about why?

**Comment by sayakpaul** [comment]
It's the `namespace` argument that we usually specify in the k8s related configuration files. We provide it to segregate our service from other services that might be running on the pods. It also makes it easier to query with a namespace. For example, if we run `kubectl get services -n $GKE_NAMESPACE` we will only get the services running against that namespace. 

It's not a must-have feature but rather a good practice.

**Comment by deep-diver** [comment]
Yeah

It makes sense, and I am just thinking about what's the good way to show this in more practical manner.

**Comment by sayakpaul** [comment]
Maybe modify the configs to include namespace?

**Comment by deep-diver** [comment]
Yeah sounds good for as a starting point. 

Since namespace is to isolate one k8s cluster into multiple virtual ones, I want to imagine having multiple namespaces for dev and prod environment for example (not sure if this is practical).

**Comment by sayakpaul** [comment]
Yeah. Maybe we need to think more about it for this project.

**Comment by sayakpaul** [comment]
@deep-diver has adapted a better methodology here: https://github.com/deep-diver/ml-deployment-k8s-tfserving
