### ISSUE TITLE
Set up another API similarly with the pure TensorFlow model for comparison

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/ml-deployment-k8s-fastapi#28]

**Comment by deep-diver** [comment]
Pure TF model with FastAPI? Or TF serving?

**Comment by sayakpaul** [comment]
First option. I think we should cover te second in a standalone project.

**Comment by sayakpaul** [comment]
TFServing is a better alternative: https://github.com/deep-diver/ml-deployment-k8s-tfserving
