### ISSUE TITLE
Setup TF Serving based deployment

### ISSUE THREAD

**Issue by deep-diver** [sayakpaul/ml-deployment-k8s-fastapi#33]
In this new feature, the following works are expected
- <del>Update the [notebook](https://github.com/sayakpaul/ml-deployment-k8s-fastapi/blob/main/notebooks/TF_to_ONNX.ipynb)</del> Create a new notebook with the TF Serving prototype based on both gRPC([Ref](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_k8s.yaml)) and RestAPI([Ref](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple)).

- <del>Update the [notebook](https://github.com/sayakpaul/ml-deployment-k8s-fastapi/blob/main/notebooks/TF_to_ONNX.ipynb)</del> Update the newly created notebook to check the `%%timeit` on the TF Serving server locally.

- Build/Commit docker image based on TF Serving base image using [this method](https://www.tensorflow.org/tfx/serving/serving_kubernetes#part_2_running_in_docker).

- Deploy the built docker image on GKE cluster

- Check the deployed model's performance with a various scenarios (maybe the same ones applied to ONNX+FastAPI scenarios)

**Comment by sayakpaul** [comment]
@deep-diver I think we should create a separate notebook for TF-serving.

**Comment by deep-diver** [comment]
@sayakpaul 

> I think we should create a separate notebook for TF-serving.

You think so? Let me create a new notebook, and let's see what's better after that then :) 

> Would be great to automate it using GitHub Actions to follow the theme of this repository.

Yeah I totally agree. I will probably create a new Github Action yaml for this one.

Also, the issue is updated according to our discussion 👍🏼

**Comment by sayakpaul** [comment]
Alright. Thank you.

**Comment by deep-diver** [comment]
Steps to build and run tf serving docker image

1. Untar tf model 
```bash
$ wget https://github.com/sayakpaul/ml-deployment-k8s-fastapi/releases/download/v1.0.0/resnet50_w_preprocessing_tf.tar.gz
$ untar -xvf resnet50_w_preprocessing_tf
$ MODEL_NAME=resnet
$ mkdir $MODEL_NAME/1
$ mv resnet50_w_preprocessing_tf/* $MODEL_NAME/1
```

2. Run the base tf serving image
```bash
$ docker run -d --name serving_base tensorflow/serving
```

3. Copy the model into the running tf serving image
```bash
$ docker cp $MODEL_NAME serving_base:/models/$MODEL_NAME
```

4. Commit the change and build a new docker image
```bash
$ PROJECT_ID=...
$ NEW_IMAGE_NAME=tfs-$MODEL_NAME:latest
$ NEW_IMAGE_TAG=gcr.io/$PROJECT_ID/$NEW_IMAGE_NAME
$ docker commit --change "ENV MODEL_NAME $MODEL_NAME" serving_base $NEW_IMAGE_TAG
```

5. Remove the base image
```bash
$ docker kill serving_base
$ docker rm serving_base
```

6. Run the new docker image by exposing two ports(gRPC and RestAPI)
```bash
$ docker run -p 8501:8501 -p 8500:8500 $NEW_IMAGE_TAG
```

or in k8s' Deployment.yaml
```yaml
  containers:
  - image: ...
    ports:
    - containerPort: 8500
      name: gRPC
    - containerPort: 8501
      name: RestAPI
```

**Comment by sayakpaul** [comment]
Yup, that is what I would have done too. 

> Run the new docker image by exposing two ports(gRPC and RestAPI)

Maybe change it to "Locally run the ..."?

**Comment by deep-diver** [comment]
@sayakpaul updated :)

**Comment by deep-diver** [comment]
tested on GKE cluster. the next step is to run a set of experiments with Locust

**Comment by sayakpaul** [comment]
Let's maybe hold off from the gRPC load test 'cause we already have a comprehensive set of experiments. What do you think?

**Comment by deep-diver** [comment]
@sayakpaul sure!

gRPC/proto is a much faster solution than RestAPI AFAIK([Ref](https://medium.com/sahibinden-technology/benchmarking-rest-vs-grpc-5d4b34360911)). 

If we see the performance of RestAPI setup on TF Serving is somewhat similar to what we have done with FastAPI server, I think it is worth to try out gRPC. Otherwise, I guess we don't need gRPC experiments

**Comment by sayakpaul** [comment]
Right. Then let's try it out. Let me also check back with my colleague regarding how they perform load tests with our gRPC microservices (at Carter) because we have a similar deployment workflow.

**Comment by sayakpaul** [comment]
It now has a standalone repository: https://github.com/deep-diver/ml-deployment-k8s-tfserving
